// Auto-generated by pipeline — do not edit manually
const REPO_LISTS = {
  "Business.Rules": [".NET"],
  "Jobs": [".NET"],
  "Microsoft.AspNetCore.MinimalApis": [".NET"],
  "Microsoft.AspNetCore.Modules": [".NET"],
  "Microsoft.EntityFrameworkCore.Utilities": [".NET"],
  "Microsoft.Extensions.Localization.Json": [".NET"],
  "PwshAnsi": ["PowerShell"],
  "PwshSetup": ["PowerShell"],
  "System.ChangeTracker": [".NET"],
  "System.Data.SqlClient.BulkOperations": [".NET"],
  "System.Diagnostics.EnhancedStackTrace": [".NET"],
  "System.Reflection.Cache": [".NET"],
  "System.Results": [".NET"],
  "Testing.Fixtures": [".NET"],
  "Testing.Toolkit": [".NET"],
};
